### ISSUE TITLE
OnBotExpired causes exception

### ISSUE THREAD

**Issue by indrif** [Etimo/diamonds#34]
api_1       |
api_1       | Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
api_1       |    at Diamonds.Rest.Controllers.BoardsController.<>c__DisplayClass9_0.<OnBotExpire>b__0(BoardBot b) in /app/Diamonds.Rest/Controllers/BoardsController.cs:line 114
api_1       |    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
api_1       |    at Diamonds.Rest.Controllers.BoardsController.OnBotExpire(Object stateObj) in /app/Diamonds.Rest/Controllers/BoardsController.cs:line 114
api_1       |    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
api_1       |    at System.Threading.TimerQueueTimer.CallCallback()
api_1       |    at System.Threading.TimerQueueTimer.Fire()
api_1       |    at System.Threading.TimerQueue.FireNextTimers()

Cleared database and restarted environment. Ran 1 bot for a minute and received exception.

**Comment by indrif** [comment]
Was still missing some updates in the code so not applicable anymore
